[tox]
isolated_build = true
skipsdist = true
usedevelop = true
envlist = {py310, py311, py312, py313}-django52


[testenv]
setenv =
    django52: DJANGO_SETTINGS_MODULE = tests.test_settingsAA5
deps=
    django52: allianceauth>=5,<6
    coverage

install_command = pip install -e ".[test]" -U {opts} {packages}

commands=
    coverage run runtests.py wikijs -v 2
    pip list
    coverage xml
    coverage html
    coverage report -m
